spring:
  security:
    oauth2:
      client:
        registration:
          kakao:

          provider:
            kakao:


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db1.c1efhs4margq.us-east-2.rds.amazonaws.com:3306/board
    username: admin
    password: 1q2w3e4r
  mail:
    host: smtp.gmail.com
    port: 587
    username: yelimim88@gmail.com
    password: koiavqegzeizbswo
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

mybatis:
  mapper-locations:
    - /mappers/*.xml

jwt:
  secret: 7pA6/5P2/r+Tby/ishTzPRwOg+CT49Pvi1pZZAfOaHTZg59e9xIE/NzAri9gNa514eAo+bxhBKN6ovjrabx9BQ==
